# Import ENV Files
spring.config.import=file:./.env[.properties],optional:file:./.local.env[.properties]
# Application name
spring.application.name=k9-club-api
# Database connection
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PWD}
spring.jpa.hibernate.ddl-auto=${JPA_HIBERNATE_DDL}
# Database seeding configuration
spring.sql.init.platform=${SQL_FILE_NAME}
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=${SQL_INIT_MODE}
# Date to Zulu UTC
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=UTC
# dit Hibernate d'utiliser UTC pour toutes les operations JDBC
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
# Get errors in response delete when test are over
server.error.include-message=always
server.error.include-binding-errors=always
# server.error.include-stacktrace=on_param   # (facultatif)
# Get env values
jwt.secret=${JWT_SECRET}
# DEBUG MODE # TODO SUPPRIMER QUAND TESTS FINIS
#logging.level.org.springframework.security=DEBUG
#logging.level.org.springframework.web=DEBUG