package com.k9club.api.dao;

import com.k9club.api.model.CourseRegistration;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Optional;


/**
 * Data Access Object (DAO) for the {@link CourseRegistration} entity.
 * <p>
 * Provides standard CRUD operations as well as custom queries to retrieve
 * course registrations by dog or by the dog's owner.
 *
 * <p>
 * Custom methods are implemented using Spring Data JPA's method naming conventions.
 * The SQL queries generated by each method are detailed in their respective comments.
 */
@Repository
public interface CourseRegistrationDao extends JpaRepository<CourseRegistration, Long> {

  /**
   * Finds a course registration by its ID and the associated dog's ID.
   *
   * <p>
   * Generated SQL query:
   * <pre>
   *   SELECT * FROM course_registration
   *   WHERE id = ? AND dog_id = ?
   * </pre>
   *
   * @param id    the registration's unique identifier
   * @param dogId the unique identifier of the associated dog
   * @return an {@link Optional} containing the registration if found, or empty otherwise
   */
  Optional<CourseRegistration> findByIdAndDogId(Long id, Long dogId);

  /**
   * Retrieves all course registrations for all dogs belonging to a given owner.
   *
   * <p>
   * Generated SQL query:
   * <pre>
   *   SELECT cr.* FROM course_registration cr
   *   INNER JOIN dog d ON cr.dog_id = d.id
   *   WHERE d.owner_id = ?
   * </pre>
   *
   * @param ownerId the unique identifier of the owner (user)
   * @return a list of {@link CourseRegistration} entities for all the owner's dogs
   */
  List<CourseRegistration> findByDogOwnerId(Long ownerId);
}